#!/bin/bash
# פתרון מהיר - יצירת Repository חדש

echo "╔══════════════════════════════════════════════╗"
echo "║  🔧 יצירת GitHub Repository חדש           ║"
echo "╚══════════════════════════════════════════════╝"
echo ""
echo "📝 צעדים לביצוע:"
echo ""
echo "1️⃣  פתח דפדפן וגש ל:"
echo "    👉 https://github.com/new"
echo ""
echo "2️⃣  מלא את הפרטים:"
echo "    • Repository name: apiryon-karaoke"
echo "    • Description: מועדון האפריון - מערכת קריוקי"
echo "    • 🔘 Public (בחר!)"
echo "    • ❌ אל תבחר README/gitignore/license"
echo ""
echo "3️⃣  לחץ 'Create repository'"
echo ""
echo "4️⃣  GitHub יציג לך מסך - התעלם ממנו!"
echo ""
echo "5️⃣  חזור לכאן והרץ:"
echo ""
echo "    cd /home/user/webapp"
echo "    git remote set-url origin https://github.com/amir9111/apiryon-karaoke.git"
echo "    git push -u origin main --force"
echo ""
echo "6️⃣  אחרי שהפקודות רצות בהצלחה:"
echo "    • לך ל-Base44 Dashboard"
echo "    • Settings → Integrations"
echo "    • Disconnect GitHub (אם מחובר)"
echo "    • Connect GitHub"
echo "    • בחר: apiryon-karaoke"
echo "    • לחץ Deploy"
echo ""
echo "════════════════════════════════════════════════"
echo "⏱️  זמן משוער: 3-4 דקות"
echo "════════════════════════════════════════════════"
